# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171005_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
